#include "stm32f4xx_conf.h"
#include <stm32f4xx.h>
#include "ws2812.h"
#include <string.h>
#include <stdio.h>
#include <stdbool.h>

struct zmiana
{
	char r;
	char g;
	char b;
	char dioda;
	int czas;
};

struct sekwencja
{
	struct zmiana zmiany[1000];
	int ilosc;
};

struct ring
{
	struct sekwencja* sekw;
	int czas;
	int index;
	int dioda_od;
};

struct sekwencje
{
	struct sekwencja sekw[6];
};
struct sekwencje Sekwencje;
struct ring Ringi[2];

//zapis wszystkich danych
void ustawSekwencje()
{
	Ringi[0].dioda_od = 0;
	Ringi[1].dioda_od = 8;

	//SEKWENCJA 1
	int l;
	l=0;
	//1 zmiana
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	//druga
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	//trzecia
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	//czwarta
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	//piata
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	//szosta
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda =1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	//siodma
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	//osma
	Sekwencje.sekw[0].zmiany[l].r = 51;
	Sekwencje.sekw[0].zmiany[l].g = 15;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 0;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 167;
	Sekwencje.sekw[0].zmiany[l].g = 31;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 1;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 255;
	Sekwencje.sekw[0].zmiany[l].g = 39;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 2;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 3;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 4;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 5;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 0;
	Sekwencje.sekw[0].zmiany[l].g = 0;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 6;
	l++;
	Sekwencje.sekw[0].zmiany[l].r = 11;
	Sekwencje.sekw[0].zmiany[l].g = 3;
	Sekwencje.sekw[0].zmiany[l].b = 0;
	Sekwencje.sekw[0].zmiany[l].czas = 0;
	Sekwencje.sekw[0].zmiany[l].dioda = 7;
	l++;
	Sekwencje.sekw[0].zmiany[l].czas = 30;
	l++;
	Sekwencje.sekw[0].ilosc = l;

//druga sekwencja
	l=0;
	int z=5;
	while(z <255)
	{
		//1 przejscie
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 7;
		l++;
		z+=10;
	}

	while(z>1)
	{
	//1 przejscie
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[1].zmiany[l].r = 0;
		Sekwencje.sekw[1].zmiany[l].g = z;
		Sekwencje.sekw[1].zmiany[l].b = 0;
		Sekwencje.sekw[1].zmiany[l].czas = 1;
		Sekwencje.sekw[1].zmiany[l].dioda = 7;
		l++;
		z-=10;
	}
		Sekwencje.sekw[1].ilosc = l;

		//trzecia sekwencja
		l=0;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;
		//druga
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;
		//trzeci
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;
		//czwarty
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;
		//piaty
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;
		//szosta
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;
		//siedem
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;
		//osiem
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas =0 ;
		Sekwencje.sekw[2].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 69;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 0;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 0;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 0;
		Sekwencje.sekw[2].zmiany[l].g = 243;
		Sekwencje.sekw[2].zmiany[l].b = 75;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[2].zmiany[l].r = 255;
		Sekwencje.sekw[2].zmiany[l].g = 255;
		Sekwencje.sekw[2].zmiany[l].b = 255;
		Sekwencje.sekw[2].zmiany[l].czas = 0;
		Sekwencje.sekw[2].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[2].zmiany[l].czas = 70;
		l++;

		Sekwencje.sekw[2].ilosc = l;

//czwarta sekwencja
	l=0;
	int x=5;
	while(x <255)
	{
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 7;
		l++;
		x+=10;
	}
	while(x>1)
	{
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[3].zmiany[l].r = x;
		Sekwencje.sekw[3].zmiany[l].g = 51;
		Sekwencje.sekw[3].zmiany[l].b = 0;
		Sekwencje.sekw[3].zmiany[l].czas = 1;
		Sekwencje.sekw[3].zmiany[l].dioda = 7;
		l++;
		x-=10;
	}
		Sekwencje.sekw[3].ilosc = l;

		//sekwencja 5
		l=0;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		//druga
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		//trzecia
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		//czwarta
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		//piata
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		//szosta
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		//siedem
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		//osiem
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 47;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 203;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[4].zmiany[l].r = 63;
		Sekwencje.sekw[4].zmiany[l].g = 0;
		Sekwencje.sekw[4].zmiany[l].b = 23;
		Sekwencje.sekw[4].zmiany[l].czas = 0;
		Sekwencje.sekw[4].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[4].zmiany[l].czas = 70;
		l++;
		Sekwencje.sekw[4].ilosc = l;

		//sekwencja 6
		l = 0;
		//kolor1
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 195;
		Sekwencje.sekw[5].zmiany[l].g = 111;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 7;
		l++;

		//kolor 2
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 100;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 0;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 7;
		l++;

		//kolor 3
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 255;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 51;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 7;
		l++;

		//kolor4
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 19;
		Sekwencje.sekw[5].zmiany[l].g = 0;
		Sekwencje.sekw[5].zmiany[l].b = 207;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 7;
		l++;

		//kolor5
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 0;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 1;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 2;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 3;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 4;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 5;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 6;
		l++;
		Sekwencje.sekw[5].zmiany[l].r = 0;
		Sekwencje.sekw[5].zmiany[l].g = 243;
		Sekwencje.sekw[5].zmiany[l].b = 75;
		Sekwencje.sekw[5].zmiany[l].czas = 20;
		Sekwencje.sekw[5].zmiany[l].dioda = 7;
		l++;
		Sekwencje.sekw[5].ilosc = l;
}

//zapala diody
void pokazZmiane()
{
	for(int i = 0; i < 2; i++)
	{
		if(Ringi[i].sekw != 0)
		{
			if(Ringi[i].czas >= Ringi[i].sekw->zmiany[Ringi[i].index].czas)
			{
				int czas_0 = true;
				struct zmiana* zm = &Ringi[i].sekw->zmiany[Ringi[i].index];
				do
				{
					diode[zm->dioda + Ringi[i].dioda_od].red = zm->r;
					diode[zm->dioda + Ringi[i].dioda_od].green = zm->g;
					diode[zm->dioda + Ringi[i].dioda_od].blue = zm->b;

					czas_0 = (zm->czas == 0);

					Ringi[i].index++;
					if(Ringi[i].index >= Ringi[i].sekw->ilosc)
					{
						Ringi[i].index = 0;
					}
					zm = &Ringi[i].sekw->zmiany[Ringi[i].index];
				}while((zm->czas == 0) && czas_0);

				Ringi[i].czas = 0;
			}
			else
			{
				Ringi[i].czas++;
			}
		}
	}
}
